services:
  - type: web
    name: flask-web
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PROD_APP_SETTINGS
        value: config.ProductionConfig

  - type: worker
    name: celery-worker
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: CELERY_BROKER_URL
        value: ${CELERY_BROKER_URL}
