services:
  - type: web
    name: flask-web
    runtime: python
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PROD_APP_SETTINGS
        value: config.ProductionConfig

  - type: worker
    name: celery-worker
    runtime: python
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    startCommand: celery -A tasks.celery_app worker --loglevel=debug
    envVars:
      - key: CELERY_BROKER_URL
        sync: false
