services:
  - type: web
    name: flask-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: CELERY_BROKER_URL
        value: amqp://guest:guest@rabbitmq:5672//
      - key: PROD_APP_SETTINGS
        value: config.ProductionConfig

  - type: worker
    name: celery-worker
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: CELERY_BROKER_URL
        value: amqp://guest:guest@rabbitmq:5672//
      - key: PROD_APP_SETTINGS
        value: config.ProductionConfig

  - type: pserv
    name: rabbitmq
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile.rabbitmq
    autoDeploy: false
