services:
  - type: web
    name: flask-web
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PROD_APP_SETTINGS
        value: config.ProductionConfig
      - key: CELERY_BROKER_URL
        sync: false

  - type: worker
    name: celery-worker
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile.worker
    dockerContext: .
    envVars:
      - key: CELERY_BROKER_URL
        sync: false
 